import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer";
import AuthProvider from "@/provider/AuthProvider";
import StateProvider from "@/provider/StateProvider";
import ConditionalNavbar from "@/components/ConditionalNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Course Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <StateProvider>
          <AuthProvider>
            <ConditionalNavbar />

            {children}
            <Footer />
          </AuthProvider>
        </StateProvider>
      </body>
    </html>
  );
}
